note:
    resource: "@NoteBundle/Resources/config/routing/note.yml"
    prefix:   /

note_liste:
    path: /liste
    defaults: { _controller: NoteBundle:Default:liste}

note_manote:
    path: /manote/{id1}/{id2}
    defaults: { _controller: NoteBundle:Default:maNote}
    methods: GET
    requirements:
      id1: '\d+'
      id2: '\d+'

note_homepage:
    path:     /
    defaults: { _controller: NoteBundle:Default:index }