NoteBundle\Entity\Note:
    type: entity
    table: null
    repositoryClass: NoteBundle\Repository\NoteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        date:
            type: datetime
        content:
            type: text
            nullable: true
        urgency:
            type: boolean
        sequence:
            type: integer
    lifecycleCallbacks: {  }
